### ISSUE TITLE
Update position, displacement, and linear velocity for arbitrary body-vertices

### ISSUE THREAD

**Issue by a-jp** [davideberly/GeometricTools#17]
Hi, 
Thanks for fixing #16.  I have a rigid body represented by an STL surface mesh.  After having called `void Update(Real t, Real dt)` of `RigidBody` I would like to update the position, displacement, and linear velocity of an arbitrary point on the rigid body. I had two questions:
1) Are those functions taking an arbitrary point baked into `GeometricTools` somewhere that I could use? I could not find them in RigidBody.
2) If not, could you point me to the appropriate equations in Game Physics?  I thought I had found them in section 2.2.2 but I'm not really sure on that.

Many thanks,
Andy

**Comment by davideberly** [comment]
Section 2.2.2 is about kinematics of a particle, so there is only a position update. The particle does not have an orientation. Section 6.5 Unconstrained Motion describes the rigid body parameters and the update of those parameters.

The equations of motion give you (among other quantities) the new position (center of mass) P1 and new orientation R1 from the previous position P0 and orientation R0. Let R0 = [U00 U01 U02], where the U-vectors are the columns. An affine coordinate system for the rigid body has origin P0 and basis vectors U00, U01 and U02. If X0 is a point in the rigid body, compute its representation in this coordinate system:  X0 = P0 + a0*U00 + a1*U01 + a2*U02. The coefficients a0, a1 and a2 are constant no matter what the coordinate system (the body is rigid).  Let R1 = [U10 U11 U12], where the U-vectors are the columns. After the Update(...) call, the corresponding X1 on the rigid body is X1 = P1 + a0*U10 + a1*U11 + a2*U22. After the update, the linear velocity of P1 is V1. The body is rigid, so at that instant of time, all points of the body have linear velocity V1.

**Comment by davideberly** [comment]
"I cache the offset ... after a call to Update in RigidBody.h." At some time you need to compute the body coordinates b for a point P in the rigid body. I prefer to think of the rigid body defined in a model space, say, in a 3D modeling package, with a model coordinate system. You can compute b in model space regardless of the simulation time. For example, suppose the model-space has origin (0,0,0) and model-space axes (1,0,0), (0,1,0) and (0,0,1). Suppose the rigid body is an axis-aligned box whose center is the model-space origin, whose axis directions are the model-space axes, and whose corners are at (+-1,+-1,+-1). With constant density, the center of mass of the box at time t=0 is C=(0,0,0). The point (1,1,1) has body coordinates (1,1,1), regardless of the simulation time. During the simulation, at time t the position of this point is given by equation (2.41), where X(t;C) is the center of mass at time t and R(t) is the orientation at time t.

My apologies, but I incorrectly stated that the (world) linear velocity is constant for all the points at time t; it is not. Yes, equation (2.43) tells you how to compute the linear velocity at a point P. Yes, for a rigid body it is the case that Dr/Dt = R db/dt =0 because body coordinates do not depend on time which implies db/dt = 0.

For unconstrained motion, Section 6.5 presents the differential equations of motion. Equation (6.69) is the state information for a rigid body and equation (6.70) tells you how the state information varies over time.  The center of mass is x(t). The linear velocity of the center of mass is v(t) = dx/dt, but with constant mass m, the state information tracks linear momentum p(t) and you know that v(t) = m p(t). The orientation is R(t) but is represented by a unit quaternion q(t). The angular velocity is w(t), but the state information tracks angular momentum L(t) and you know that L(t) = J(t)w(t) where J(t) is the inertia tensor of the rigid body. Equation (6.66) tells you how to compute the inertia tensor from the orientation R(t) and the body inertia tensor measured in the  model space coordinates.

Here is how this all fits together for a simulation, illustrated at time t = 0 with a time step of h.

1. Select model space coordinates and use these to set up the time t = 0 parameters of the simulation.
2. Compute the center of mass x(0) = C.
3. Compute the body inertia tensor J_body, typically the matrix whose columns are the principal inertia axes.
4. Choose an initial orientation matrix R(0).
5. Compute a unit quaternion q(0) representing R(0).
6. Choose an initial linear velocity v(0) for the center of mass x(0).
7. Compute initial linear momentum to p(0) = v(0)/m.
8. Choose an initial angular velocity w(0) for the center of mass x(0).
9. Compute a (not-necessarily-unit) quaternion omega(0) representing w(0).
10. Compute L(0) = R(0) J_body Transpose(R(0)) w(0).

At this point you have the initial value for the equations of motion (6.70); that is, you know x(0), q(0), p(0) and L(0).

For simplicity of illustration, suppose you numerically solve (6.70) using Euler's method. The force function is Force(...) and the torque function is Tau(...) and typically has inputs of time and state information. You obtain

1. x(h) = x(0) + h p(0)/m
2. q(h) = Normalize(q(0) + h omega(0)/2)
3. p(h) = p(0) + h Force(...)
4. L(h) = L(0) + h Torque(...)

Extract linear velocity v(h), orientation R(h) and angular velocity w(h) for the center of mass at x(h).

1. v(h) = p(h)/m
2. R(h) is computed from the unit quaternion q(h)
3. w(h) = R(h) Inverse(J_body) Transpose(R(h)) L(h)

Given a point with body coordinates b,

1. world position P = x(h) + R(h) b
2. world velocity is V = v(h) + Cross(w(h), R(h) b).

In RigidBody.h:

1. mMass is m and mInvMass is 1/m
2. mInertia is J_body and mInvInertia is Inverse(J_body)
3. mPosition is x(h)
4. mQuatOrient is q(h)
5. mLinearMomentum is p(h)
6. mAngularMomentum is L(h)
7. mRotOrient is R(h)
8. mLinearVelocity is v(h)
9. mAngularVelocity is w(h)

**Comment by a-jp** [comment]
Thank you for the detailed reply. Much appreciated.

**Comment by davideberly** [comment]
You are welcome.
