### ISSUE TITLE
Advice/Guidance: triangle-triangle intersection in 3D with resulting (if any) closed-line-loop-polygons

### ISSUE THREAD

**Issue by a-jp** [davideberly/GeometricTools#19]
Hi,

Is there an implementation in GeometricTools of triangle-triangle intersection in 3D which also returns, if any, the closed line loops of the resulting polygons that result from the intersection?  I found triangle-triangle in section 11.5.4 of your book Geometric Tools... which is great, but I wondered if the code was provided here?

I really need the resulting N closed-polygon-line-loops, if any, that define the N-polygons produced as a result of the intersection of the two triangles.  Could you point me in the right direction for this?

Thanks,
Andy

**Comment by davideberly** [comment]
When two 3D triangles intersect, the top-level of the query needs to determine whether or not the triangles are coplanar. If the intersecting triangles are not coplanar, they can intersect in a point or a line segment. There is no "closed-polygon-line-loop." May I assume you are referring to the coplanar case? In this case, the triangles can overlap in a convex polygon. Are you looking for code that computes these polygons (if any)? If this is what you want, you can transform the triangle vertices from 3-tuples to 2-tuples. If the common plane contains point P, has normal vector N, and U and V are vectors in the plane so that {U,V,N} is a right-handed orthonormal set (unit-length vectors, mutually perpendicular, N = Cross(U,V)), you can write a vertex Q = P + x*U + y*V, where x = Dot(U,Q-P) and y = Dot(V,Q-P). Now you have two triangles in 2D. The file IntrTriangle2Triangle2.h has a find-intersection query, FIQuery<Real,Triangle2<Real>,Triangle2<Real>>, that computes the point, segment or polygon of the intersection (if there is an intersection).

**Comment by a-jp** [comment]
Many thanks for your help here.
