### ISSUE TITLE
Naming inconsistency for ray intersections against different geometries.

### ISSUE THREAD

**Issue by mgamito** [davideberly/GeometricTools#21]
There is some inconsistency in the naming of some of the intersection objects. For example, the Sphere3 class has a FIQuery object with fields like `numIntersections` and `parameter[]` . In contrast, the FIQuery for OrientedBox3 has `numPoints` and `lineParameter[]`.

If the naming was consistent, it would be possible to write a generic intersection function:

```
template <typename GeometricObject>
bool intersect(const GeometricObject& object, const gte::Ray3<float>& ray)
{
    gte::FIQuery<float, gte::Ray3<float>, GeometricObject> query;
    auto intersection = query(ray, object);

    if(intersection.intersect)
    {
        float nearestT = intersection.parameter[0];
        unsigned numIntersections = intersection.numIntersections;
        ...
    }
}
```

I guess making this change would break already existing code so I'm not sure how viable it is but I thought I would mention it because, as I explained, it would allow for more consistent coding going forward.

**Comment by davideberly** [comment]
I am aware of inconsistencies of naming and style in GTE. I started posting code on the Internet back in the early 1990s. As with many code bases, the evolution eventually requires a rewrite/clean-up. Consistency is one of the goals for my GTL project among other goals such as performance, support for exact arithmetic, better unit testing (and fixing whatever bugs I find along the way). The current code base is 30 years worth of code needing some help...

The generic behavior you mention appears to be for object-ray intersection testing, which can be even more generic for line/ray/segment (rather than just ray). The difficulty of providing a generic object-object intersection library is that the query results are generally specific to object type. There are situations where you need to provide inputs to the query. For example, a geometric algorithm that uses bisection internally most likely needs a user-specified maximum number of iterations. GTE intersection/distance queries with query(object0,object1) do not always provide a generic mechanism for such control. A GTL goal is to do so, perhaps by "result = query(object0,object1,controls)". Now there is the question of persistence of the input "controls". Passing as an argument to the query, the persistence is only during the query call. However, there might be controls that persist for the lifetime of the query object, in which case there might be input controls passed to the query constructor that are stored as query-class members. Well, more consistency to worry about. Probably it is easier to achieve consistency by having stateless queries: no non-static class members, all information passed/returned via the operator()(...) calls.

At any rate, I have added comments to my internal development notes to remind me to make the names as consistent as possible. In the short term, if you have a subset of GTE code for which consistent naming will help you, let me know what that subset is. For example, if your goal is generic object-line intersection code, I am willing to modify the GTE interfaces for the appropriate query classes to support that.

I very much appreciate your feedback about the code. This helps make the code base better for everyone to use.

**Comment by mgamito** [comment]
Hello David,

Thank you for your detailed reply. Let me give some more information about why I mentioned this issue. I use GTE in a path tracer where I need to test ray intersections against a family of procedural objects like aligned boxes, oriented boxes, spheres, ellipsoids and cylinders. Rather than trying to figure out the minutiae of those intersections myself, I have learned to rely on the GTE and it does a very good job for me. Because these are all convex objects, there are always at most two intersections with a ray. While writing the code to drive the FIQueries, I started to notice a lot of similarities (apart from the naming inconsistency I mentioned), which made me think that it should be possible to write a templated generic intersection routine like the one I showed above that would work at least for this subset of geometric objects. At the moment, I need to maintain a separate intersection code for boxes because of their different naming but I can well understand that these were written at a different time and so did not follow the same naming conventions.

Since I am mentioning this, I can also mention that I found some bugs when trying to intersect against single rectangles and discs, for which I use a box with one of the dimensions being zero or a cylinder with a height of zero, respectively. Although the documentation seems to indicate that such degenerate flat objects are allowed, the intersection routines don't always work so well. In practice, I set the zero dimension to a small value like 1.0e-6 and I get the desired behaviour so this is not an issue for me.

Thank you for taking the time to consider these issues.

**Comment by davideberly** [comment]
In the discussion, LRS refers to {line,ray,segment}.

I have modified the LRS-convex_volumetric_object code to use consistent naming. The modified code is currently being unit tested.

The LRS-box code is intended for boxes of positive volume. What you need is a LRS-rectangle query, similar to the LRS-triangle query I already have. The LRS-cylinder code is intended for cylinders of positive volume. What you need is a LRS-disk query. I will add these items to my pending-task list. The LRS-convex_planar_object (in 3D) code also needs to be modified to have consistent naming, this to support your desire to intersect rays with rectangles and disks. The LRS-triangle and LRS-plane queries in GTE have 1-tuple values for 'parameter' and 'point'. I plan on modifying these to 2-tuples to be consistent with the idea that the intersection set is empty, a point, or a segment.

I will post GTE 5.11 with these changes once I am finished with the modifications/testing.

**Comment by davideberly** [comment]
I posted modified files for Intr[linear]3[object]3.h, where linear is in {Line, Ray, Segment} and where object is in {AlignedBox, Capsule, Cylinder, Ellipsoid, OrientedBox and Sphere}. These have consistent naming, and the blocks that refine the t-parameters from line-object queries for potential update by ray-object and segment-object queries were also modified to be consistent.

**Comment by mgamito** [comment]
Thank you, David. That is much appreciated. It will lead to simpler code when driving the GTE.

**Comment by davideberly** [comment]
You are welcome. The remaining intersection code needs a review, but I will get to that during the port from GTE to GTL.
