### ISSUE TITLE
QuadricSurface and ApprQuardratic3 Documentation/Comments

### ISSUE THREAD

**Issue by intrinsicD** [davideberly/GeometricTools#23]
In ApprQuadratic3.h the comments say 
  
>   // ...K = C[0],
>     // B = (C[1],C[2],C[3]), and A is a 3x3 symmetric matrix with
>     // A00 = C[4], A11 = C[5], A22 = C[6], A01 = C[7]/2, A02 = C[8]/2, and
>     // A12 = C[9]/2 ...

and you pass the eigenvector as is into the coefficients
          
>   es.GetEigenvector(0, &coefficients[0]);

But in QuadricSurface.h the matrix A is filled with
         
>  mC = mCoefficient[0];
>             mB[0] = mCoefficient[1];
>             mB[1] = mCoefficient[2];
>             mB[2] = mCoefficient[3];
>             mA(0, 0) = mCoefficient[4];
>             mA(0, 1) = (Real)0.5 * mCoefficient[5];
>             mA(0, 2) = (Real)0.5 * mCoefficient[6];
>             mA(1, 0) = mA(0, 1);
>             mA(1, 1) = mCoefficient[7];
>             mA(1, 2) = (Real)0.5 * mCoefficient[8];
>             mA(2, 0) = mA(0, 2);
>             mA(2, 1) = mA(1, 2);
>             mA(2, 2) = mCoefficient[9];

The offdiagonal elements don't fit the comments, correct?

**Comment by davideberly** [comment]
The two files were written at different times. The ApprQuadratic3.h file lists the coefficients in the order (1,x,y,z,xx,yy,zz,xy,xz,yz) whereas the QuadricSurface.h file lists the coefficients in the order (1,x,y,z,xx,xy,xz,yy,yz,zz); these are different orders. Each header file has no dependency on the other header file, so when used individually, the ordering is irrelevant. I assume, though, that you are fitting using ApprQuadratic3 and then trying to classify the results by using QuadricSurface.

I am deprecating ApprQuadratic{2,3}.h in GTL for the general fitting because typically a user has a specific type of quadric surface in mind. The classification is sensitive to the quality of the input data and to floating-point rounding errors, so the result might not be what one wants. ApprQuadratic2.h has ApprQuadraticCircle2, but a better fitting algorithm is FitUsingSquaredLengths in ApprCircle2.h. Similarly, ApprQuadratic3.h has ApprQuadraticSphere3, but a better fitting algorithm is FitUsingSquaredLengths in ApprSphere3.h.

In the short term, I will change the order of the coefficients in ApprQuadratic{2,3}.h to match the ordering of QuadricSurface.h. The ordering of QuadricSurface.h is consistent with that of Hyperellipsoid.h (which is Ellipse2 and Ellipsoid3 for N = 2 and N = 3).  Part of the porting to GTL involves replacing C-style arrays such as "Real coefficients[10]" by "std::array<Real, 10> coefficients". Regardless, the change to the coefficient order will break code that relies on the old ordering, so the check-in comments will mention this.

**Comment by davideberly** [comment]
I modified ApprQuadratic{2,3}.h as mentioned in my previous comment. The files have been posted. Unit tests show that the reordering is producing coefficients that match those of the old code with the reordering applied to the output of the old code.
