### ISSUE TITLE
SymmetricEigensolver3x3 is only robust when fast math is not used

### ISSUE THREAD

**Issue by jeffp-seequent** [davideberly/GeometricTools#24]
We have several matrices that cause the SymmetricEigensolver3x3 to compute NaNs when fast math is turned on in our code. 

For example
```
| 90.270270270270231,       8.6380368027297633e-16,    -3.4176970386003999e-15 |
| 8.6380368027297633e-16,   179.99999999999986,        0.00000000000000000     |
| -3.4176970386003999e-15,  0.00000000000000000,       90.270270270270231      |
```

The eigen vectors are the x-, y-, and z-basis vectors and the eigen values are the diagonal, as the very small values are essentially zero.

This is because the fast math option replaces multiple divides by the same value as a 1.0/value followed by multiplications (a usually valid transformation). This is fine and does not indicate a bug, but it does show that the code is not robust to different methods of compilation.

The offending method is GetCosSin, specifically, https://github.com/davideberly/GeometricTools/blob/2381a3bd68ce1b2b0aeb53f5266af104dbba1c92/GTE/Mathematics/SymmetricEigensolver3x3.h#L352-L356

If the value of maxAbsComp is denormalized, as happens when solving the given matrix above, then 1.0/maxAbsComp (a value computed by the machine code generated by the compiler with fast math turned on), will be infinity. The result of the overall math with this transformation is NaN, resulting in NaNs for all eigen vectors.

For now we have mitigated the issue by compiling the entire header using precise math, as follows (in Visual Studio on Windows)
```
#pragma float_control( push )
#pragma float_control( precise, on )
#include "GteSymmetricEigensolver3x3.h"
#pragma  float_control(pop)
```

It is best, however, to not have to do this for all the code in the header.

Again, this does not indicate a bug with the code, but it does show that the code is not robust to different methods of compilation. This is usually the case for floating point libraries. We thought, instead, that you would be interested in this nuance.

Should we assume that the Geometric Tools library requires precise floating point math in order to be robust?

**Comment by davideberly** [comment]
"Should we assume that the Geometric Tools library requires precise floating point math in order to be robust?" YES. It is difficult to write robust code using "precise." Changing this to "fast" makes it even more difficult. Compiler optimizations that are effectively unknown (and presumably context specific) are undesirable, in my opinion. Even with "precise" this can be a problem. Different compilers can use different types of registers (32-bit register? 64-bit register? Extended precision 80-bit register? Copying from a high-precision register to a lower-precision register?)

In my test code for your example, the outputs of the eigensolver for your example are the same whether "precise" or "fast" when the 'aggressive' parameter is set to 'false'. When that parameter is set to 'true', the "fast" version generates the NaNs. The non-aggressive code decides convergence occurs when the floating-point sum of two consecutive diagonal terms is the same as the floating-point sum of those two terms plus the adjacent off-diagonal term. The intuition is that the off-diagonal term is so small compared to the diagonal terms that it is effectively zero.

The aggressive code attempts to force the off-diagonal terms to zero. For "precise", this is a reasonable choice, but for "fast" you do not want to do this (for the reasons you mention).

Regardless, I will revisit GetCosSin and try to modify it to be robust when "fast" is used.

Thank you for taking the time to report this problem.

**Comment by jeffp-seequent** [comment]
Thanks for the prompt reply. We will more fully investigate the aggressive parameter to see if setting it to false is suitable in our cases.

**Comment by davideberly** [comment]
You are welcome. Whether or not the 'false' flag works for you, I will revisit the code anyway. I doubt it will require much to fix the problem.

**Comment by davideberly** [comment]
I posted a revised SymmetricEigensolver3x3.h that fixes the /fp:fast problem. I also revised the code and the PDF file describing it so that they match. The PDF has more details about the algorithm that were not in the previous version. See the commit notes for the link to the PDF.
