### ISSUE TITLE
MinimalCycleBasis 

### ISSUE THREAD

**Issue by WREQI** [davideberly/GeometricTools#25]
Whether to support technology with a mixture of arcs and straight lines

**Comment by davideberly** [comment]
To be robust, the minimal cycle basis code is designed to use arbitrary-precision arithmetic. If you use floating-point arithmetic, rounding errors can lead to an incorrect result. Implementing an algorithm that supports arcs and line segments is more complicated. Obtaining a robust algorithm has the same issues regarding arbitrary-precision versus floating-point. I believe that using the QFNumber class (instead of BSNumber class) can lead to an exact result (using arbitrary-precision). QFNumber allows you to compute exact results when the expressions include square-root terms. QFNumber<T,1> implements arithmetic of numbers x+y*sqrt(d0), where x, y and d0 are rational. QFNumber<T,2> implements numbers u+v*sqrt(d1) where u = x0+y0*sqrt(d0) and v = x1+y1*sqrt(d1) with rational numbers x0, y0, d0, x1, y1, d1 (and d0 != d1). The more square root terms with distinct d-arguments, the more expensive to compute. The number of such terms depends on the geometric problem at hand. I have to work through the cycle basis ideas to determine how many square root terms occur.

I will add this to my list of requests to be considered, but I doubt I can produce an implementation in the short term.

**Comment by davideberly** [comment]
Just a thought. If you approximate each arc by a polyline so that the polyline does not intersect any other edge or arc, you can use the current minimal cycle basis code. Once you have the cycles, you can replace the polylines by the arcs that generated them.
