### ISSUE TITLE
Conflicts between the XXEngine classes and BaseEngine

### ISSUE THREAD

**Issue by tbridel** [davideberly/GeometricTools#33]
Dear all,

I was just trying to compile the latest version of GTE using the provided CMake workflow, and I hit a lot of conflicts between the BaseEngine class and its daughters, especially due to the implicit overriding of some methods that now (from C++ 11) require the _override_ keyword.
I could fix it and start a new Pull request, but I do not know whether you would rather mark the daughter methods as override or remove the inheritance or remove BaseEngine ....

Anyways, here is the [cmake.log](https://github.com/davideberly/GeometricTools/files/7740885/cmake.log) that I got by running:

```
mkdir -p build && cd build
#-
cmake \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++ \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_RELEASE_LIB:BOOL=TRUE \
-DBUILD_SHARED_LIB:BOOL=TRUE \
-S .. -B .
#-
cmake --build . --config Release --parallel 16
```

I use LLVM v13 (AppleClang 13.0.0.13000029) on a MacBook Pro with an Intel i7 chip.

Looking forward to hearing from you, 
Best,

Thibault

**Comment by davideberly** [comment]
Apparently the gcc compilers I use to build the distribution on Ubuntu and on Fedora are not forcing use of "override". I do not have a Macintosh computer to test the build. The Microsoft compiler default in Visual Studio is not reliable, allowing code to compile that gcc does not. On gcc I have warnings set to "all", but that appears not to be consistent among compilers. I have warnings set to Level 4 on MSVS. I have not tried setting to "all" because years ago, doing so would generate a massive amount of complaints from Windows.h.

At any rate, I will make the changes, adding override. Eventually I will rewrite the graphics engine code (and add DX12 and Vulkan support), but that will not happen in the near future.

**Comment by tbridel** [comment]
Ok, thank you ! 
I indeed found that the Clang compiler is often more severe than Gcc regarding the standards … especially the latest versions beyond 11.

**Comment by davideberly** [comment]
I appreciate your taking the time to make all the code modifications.

**Comment by tbridel** [comment]
You are very welcome !
