### ISSUE TITLE
polygon with arc sides ?

### ISSUE THREAD

**Issue by owai1980** [davideberly/GeometricTools#39]
_I don't know where to ask this question, sorry if i'm at the wrong place._

I work in 2D and I need a "Polygon2" object with some arc sides. (some or all Segment2 replaced by Arc2 objects). I think it is not yet possible. Do you have any advice? Will this feature be available one day?

In 3D, the class Cylinder3 has both Arc and Line segments ... so maybe it is "almost possible" ?

I need to do boolean operations like AND, OR, XOR, ... on those "2D arc polygons".

Thank you!

**Comment by davideberly** [comment]
I do not have support for "poly objects" in 2D with segments and arcs. The Boolean operations I currently have are for polygons with segments. And the polygons have to be what I call polysolids (from a document written by H. Maynard and L. Tavernini). Each polysolid decomposes the plane into two disjoint regions (a 2-coloring of the plane). One region is bounded, the other is unbounded. Unfortunately, the Boolean operations in GTE use binary space partitioning (BSP) which is notorious for generating too many unnecessary vertices (my BSP code is old and generally sucks). My "infinite todo list" has an item to use sort-and-sweep instead to find all-pairs intersection points of segments, but I do not plan on implementing this until I finish the GTL code. And the completion date for GTL is unknown because I can work on this only when not doing contract programming.

The sort-and-sweep approach works for segments and arcs. Intersecting segment-segment generates one point (or the segments are equal and you have infinite points). Intersecting segment-arc generates one or two points. Intersecting arc-arc generates one point, two points or infinite points if the arcs are on the same circle.

**Comment by owai1980** [comment]
thank you for your clear answer. i understand.

you are right about everything. i'll try myself using the Segment2 and Arc2 objects,... but i'm not sure i could write code as clean as you do !!

thank you for your great work so far!

**Comment by davideberly** [comment]
You are welcome to ask me questions while you try this (contact via my email, not github). The sort-and-sweep idea is shown in RectangleManager.h, although that class is designed to support broad-phase collision culling. It has code to update the set of overlapping pairs of rectangles after the rectangles move. The Boolean operations do not need this. The rectangles are axis-aligned bounding boxes for the segments and arcs. Once you find a pair of overlapping boxes (potentially intersecting primitives), you then apply the actual find-intersection queries (segment-segment intersection, segment-arc intersection, arc-arc intersection). The supporting classes for this are IntrSegment2Segment2.h, IntrSegment2Arc2.h and IntrArc2Arc2.h. Once you have found all the intersection points, you have a collection of segments and arcs (some of them subsets of what you started with). The Boolean operation part of the algorithm is to identify which segments and arcs go with the AND, OR, DIFF, and XOR outputs.
