### ISSUE TITLE
distArc2Point2

### ISSUE THREAD

**Issue by owai1980** [davideberly/GeometricTools#47]
Hello

This is more a "feature request" ... I need a function to calculate the distance from a 2D point to a Arc2 ...
I can easily get the distance from the point to the full circle... but for an Arc2 it's more difficult :-)

can you help or give clue?

thank you ... again!

Johan

**Comment by davideberly** [comment]
I will add an implementation of distance(point2,arc2). I should have the time in a couple of days. For an arc subtending an acute angle, you need only determine whether the incoming point is in the 2D wedge defined by the circle center and the arc. If so, you compute the distance to the circle (this is a Voronoi argument). Otherwise, the point is outside the wedge and you compute distance to the appropriate arc endpoint. For an arc subtending an obtuse angle, I believe the same idea works, but I need to think about it.

**Comment by owai1980** [comment]
You are right, your idea sounds good! 👍 👍

I'll be happy to test your work!

Thank you.. Again!

Le ven. 18 nov. 2022 à 20:02, David Eberly ***@***.***> a
écrit :

**Comment by davideberly** [comment]
I posted the 2D distance queries for point-circle and point-arc. The file names are DistPoint2Circle2.h and DistPoint2Arc2.h. I have unit tested these, but if you discover any problems with the code, please let me know.

**Comment by owai1980** [comment]
Wow thank you so much! I will check this tomorrow morning!

👍

Le jeu. 1 déc. 2022 à 18:56, David Eberly ***@***.***> a
écrit :

**Comment by owai1980** [comment]
I just read  your code...  Looks prefect!

Just a little idea...  In the distarc2point2 : 
You wrote this

                   T length0 = std::sqrt(sqrLength0);
                    T length1 = std::sqrt(sqrLength1);
                    if (length0 <= length1)
                           ... 

I think (but I might be wrong) at we can compare the squared length in the if(),  and compute only ONE OF the sqrt inside the if... Else... 
So we avoid one "sqrt" call. 

Right? 

Thank you again for your great work! 👍 

Johan

**Comment by davideberly** [comment]
Modified and uploaded. Thanks.
