### ISSUE TITLE
glt Multiarray error

### ISSUE THREAD

**Issue by WuyangPeng** [davideberly/GeometricTools#73]
bool operator< (Multiarray const& other) const
        {
            if (Lattice<OrderLtoR>::operator<(other))
            {
                return true;
            }
            if (Lattice<OrderLtoR>::operator<(other))     // here >
            {
                return false;
            }
            return  mContainer < other.mContainer;
        }

**Comment by davideberly** [comment]
Thank you for reporting this bug. The MultiarrayAdapter class has the correct comparison. I need to look at the unit test to see why this bug was not detected. At the moment I am on travel and do not have access to my unit test harness. When I return I will post the bug fix and modify the unit tests accordingly.

**Comment by davideberly** [comment]
Fixed and posted.
