### ISSUE TITLE
Segment3-Rect3/Square3 intersection finding

### ISSUE THREAD

**Issue by a-jp** [davideberly/GeometricTools#79]
Hi,

I'm currently using your Seg3-Plane3 intersection tests, but my planes really are axis aligned faces of a 3D cube, so each is a square (not a rectangle, if that matters).  Can I check that I have not missed anything and that seg3-Rect3 or seg3-Square3 are not currently implemented?

Would you have any recommendations if I'm interests in the intersections of a finite sized plane in 3D i.e. a square/rectangle with a finite length edge (segment) in 3D?

Many thanks,
Andy

**Comment by davideberly** [comment]
I do not have explicit implementations in 3D for segment-rectangle. I will add those. Until I do, you can use the segment-triangle intersection code IntrSegment3Triangle3.h. Split your rectangle into 2 triangles and execute 2 segment-triangle queries.

**Comment by davideberly** [comment]
Using segment-triangle queries, if both triangles report an intersection, then the intersection point is either exactly on the diagonal or--because of floating-point rounding errors--near the diagonal. In either case, compute the average of the two intersection points and call that the segment-rectangle intersection.

**Comment by davideberly** [comment]
I should have mentioned in my previous comment that you can have a problem if the segment intersects the rectangle in a single point but the segment-triangle queries both report no-intersection. This would be caused by floating-point rounding errors (a common problem in ray tracing a triangle mesh).

Regardless, I posted IntrLine3Rectangle3.h, IntrRay3Rectangle3.h, and IntrSegment3Rectangle3.h for test-intersection and find-intersection queries. A sample application was added to illustrate and for testing: GeometricTools/GTE/Samples/Intersection/IntersectLineRectangle. I have a brief description of this sample at my website together with some screen captures.

**Comment by a-jp** [comment]
Thank you so much for doing this. I'll try them tomorrow. Just to understand further, which point would be detected that a tri-segment would not return? Are you thinking diagonal?
Thanks

**Comment by davideberly** [comment]
Are you asking for triangle-rectangle intersection in 3D? If so, what do you mean by "Cartesian aligned"? Are the axes of the rectangle in the set {(1,0,0),(0,1,0),(0,0,1)}.

It will be helpful if you open a new issue for this. Re-opening the current issue makes it appear as if the segment3-rectangle3 intersection issue is not yet complete. Thank you.
