### ISSUE TITLE
bug or precision problem in "IntrLine2Circle2.h"

### ISSUE THREAD

**Issue by owai1980** [davideberly/GeometricTools#94]
Hello, 

i found this problem... i know that the "double" precision is not good, but anyway, i tell you... who knows :-)

 the line is tangent to the exact bottom of the circle (1 intersection)... 
here's the code ... no intersection found.

if i change the x of the line origin position , the code gives 0, 1 or 2 intersections...

```
gte::Vector2<double> lineOrig({ 92.0, 770.0 });
//gte::Vector2<double> lineOrig({ 0.0, 770.0 });
gte::Vector2<double> lineDir({ 1.0, 0.0 });
gte::Line2<double> L(lineOrig, lineDir);

gte::Vector2<double> center({ 530.02631651848, 1380.0 });
//gte::Vector2<double> center({ 530.0, 1380.0 });
gte::Circle2<double> C(center, 610.0);

gte::FIQuery<double, gte::Line2<double>, gte::Circle2<double> > mFIQuery;
auto res = mFIQuery(L, C);

int nbi = res.numIntersections;
```

thank you for your time...

johan

**Comment by owai1980** [comment]
i changed my code to use "gte::BSRational<gte::UIntegerAP32>" instead of "double" ... and everything works fine...

**Comment by davideberly** [comment]
You have a rounding error even before calling the intersection query. The x-value of the center is typed as 530.02631651848, which cannot be exactly represented as a double-precision number. If you run in a debug build, place a breakpoint after the Circle2<double> constructor call, and then look at C.center[0] in a watch window, you will see 530.02631651848003. According to the IEEE Floating Point Standard, 530.02631651848003 is the double-precision number closest to the theoretical value 530.02631651848 (with default rounding mode of round-to-nearest-ties-to-even).

In your code sample I added "using Numeric = double;" and declared objects such as Vector2\<Numeric\>, Line2\<Numeric\> and Circle2\<Numeric\>. Running the experiment, you see 530.02631651848003 in the watch window, and the number of intersections is 0.

Now if you switch to BSRational\<UIntegerAP32\>, the rounding error STILL occurs because 530.02631651848 is passed as a 'double' to the BSRational\<UIntegerAP32\> constructor, and you have the representation error. However, the number of intersections  is computed to be 1. There are no rounding errors other than the representation error, and the block of DoQuery for "discr == 0" is entered (so no std::sqrt call is made, which would involve a rounding error).

The recommended way to get an exact rational representation of a 'double' number is to use the BSRational constructor whose input is a string.

```
C.center[0] = BSRational<UIntegerAP32>("530.02631651848");
```

**Comment by owai1980** [comment]
Thank you for your answer, always interesting to understand what is going
under!...

It's good to know that even the bsrational could lead to incorrect result
of the input numbers come from non precise double...

I keep this for later reference!

Thanks

Johan


Le mer. 4 sept. 2024 à 21:03, David Eberly ***@***.***> a
écrit :

**Comment by davideberly** [comment]
The IEEE Floating Point Standard also includes information about how to read/write floating-point numbers. Suppose you want to write floating-point numbers to a text file. Late you want another application to read those floating-point numbers. The important question is: Given a binary format floating-point number, how many digits do you write so that when that text number is read, it represents the binary format number you started with?

For me, this issue arises when someone uses computational geometry code to compute using floating-point numbers, the result is incorrect, and they write out the input of the computational geometry code to a text file and send it to me. When I read that file, the computational geometry code might work properly. The problem is that after I read the file into floating-point numbers in memory, I might not have exactly the same binary representations that the bug reporter has. Convex hull computation and Delaunay triangulation are classic examples where folks have reported bugs and send me text files with an insufficient number of digits for each floating-point number.

To avoid this, I request writing the floating-point numbers to a binary file and send that. Alternatively, the floating-point numbers can be interpreted as arrays of uint8_t and written as text. On read, the uint8_t values are parsed to recreate the binary data exactly.

**Comment by owai1980** [comment]
I agree and have encountered this problem many times too when exporting to
xml, json,...

You are right, I should use binary format, to be sure it's exact.

Le jeu. 5 sept. 2024 à 08:38, David Eberly ***@***.***> a
écrit :
